### ISSUE TITLE
influxdb 0.9.0

### ISSUE THREAD

**Issue by nemesisdesign** [bitlabstudio/django-influxdb-metrics#1]
The next release of InfluxDB is going to introduce some backward incompatible changes.

Do you plan to upgrade?
If yes I might be able to help out.

I'd also love to add a middleware to track number of requests and time spent generating responses.

Federico

**Comment by mbrochh** [comment]
I plan to maintain this, so as soon as i update my influxdb instance, I
also gonna update this repo, but I can't tell you how soon that will be.

by the way, there is already a middleware inthis repo that tracks requests
and response times.

If you are faster than me, I'll be happy to merge pull requests

**Comment by nemesisdesign** [comment]
Hi Martin,

there are quite a few breaking changes that will require quite a deal of changes, probably the apply_prefix and apply_postfix won't have sense with the introduction of tags.

At the moment I'm just copying and pasting what I need for a prototype but as soon as what i'm doing grows I'll come back here.

I hope that by that time you'll have had time to take a look at influxdb 0.9.0 to be aware of what needs to change so that you won't be scared when others will start sending patches :-)

Federico

**Comment by sunjay** [comment]
+1

**Comment by saily** [comment]
@Tyrdall as far as i can see, this issue was already resolved and could be closed.
