### ISSUE TITLE
INFLUXDB_DISABLED = True still sends user_logged_in event 

### ISSUE THREAD

**Issue by seanauriti** [bitlabstudio/django-influxdb-metrics#13]

**Comment by Tyrdall** [comment]
@seanauriti Can you provide more info?

**Comment by seanauriti** [comment]
I ended up removing it from INSTALLED_APPS to stop it from trying to send the event.  A way to fix this would be to turn off the user_logged_in_event by default and allow it to be an option.

**Comment by Tyrdall** [comment]
@seanauriti ``INFLUXDB_DISABLED`` is disabling all writing actions.

Here's the user event: https://github.com/bitlabstudio/django-influxdb-metrics/blob/master/influxdb_metrics/models.py#L12

Here's how to disable writing data: https://github.com/bitlabstudio/django-influxdb-metrics/blob/master/influxdb_metrics/utils.py#L41

**Comment by seanauriti** [comment]
Ok looks good.  Maybe it works now, if it happens again I'll reopen.  Thanks for the info.

**Comment by sLuvpreet33** [comment]
@seanauriti  did u write points to the influxdb manually OR this app automatically does that ?
