### ISSUE TITLE
InfluxDB write_data using wrong CELERY_BACKEND_URL

### ISSUE THREAD

**Issue by Archarachne** [bitlabstudio/django-influxdb-metrics#15]
In the project I'm working on we have different settings for dev, stage and prod environments. Also `CELERY_BACKEND_URL` is set differently. Our backend is set to redis and yet the package tries to use RabbitMQ. Celery is 4.0.2, all workers are running with -A option. 

What I'm getting after setting `INFLUXDB_USE_CELERY=True`:

```
...lib/python2.7/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
...lib/python2.7/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
...lib/python2.7/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
OperationalError: [Errno 111] Connection refused
```

**Comment by Tyrdall** [comment]
@Archarachne Were you able to find out what's wrong? I assume this is an issue of your celery setup, since our celery integration is very basic.
