### ISSUE TITLE
influx not showing django database

### ISSUE THREAD

**Issue by sLuvpreet33** [bitlabstudio/django-influxdb-metrics#17]
I have installed as stated in the welcome page.

Here is my settings file,

`INFLUXDB_HOST = '127.0.0.1'`
`INFLUXDB_PORT = '8086'`
`INFLUXDB_USER = 'first'`
`INFLUXDB_PASSWORD = 'password'`
`INFLUXDB_DATABASE = 'djangodb'`

`# Seconds to wait for the request to the influxdb server before timing out
INFLUXDB_TIMEOUT = 5`

I have a simple model, 

`class Bike(models.Model):
     name = models.CharField(max_length=100)`

I created database 'djangodb' in influx shell,

But it is empty. Can you please help and tell me why it is still empty?
What will it have? What am I doing wrong?

**Comment by Tyrdall** [comment]
@sLuvpreet33 Did you write points to the influx database?

**Comment by sLuvpreet33** [comment]
We have to manually write points to the database ? Can you give me some kind of working example please ?

Also, the influxdb_get_postgresql_size is not working.
`
luvpreet@DHARI-Inspiron-3542:~/test_venv_wrapper/influxtest$ ./manage.py influxdb_get_postgresql_size first test
`

first = user in the postgres
test = name of the database

i do have a pgpass file also in the same location.

**Comment by Tyrdall** [comment]
@sLuvpreet33 What means it is not working?

Well, did you fill the influx db with data? Otherwise it will remain empty for sure.

**Comment by sLuvpreet33** [comment]
sorry bro @Tyrdall I did not get it. What should I write to influx ? anything ? in what format ?

What I meant by that it is not working is the following, 

`luvpreet@DHARI-Inspiron-3542:~/test_venv_wrapper/influxtest$ ./manage.py influxdb_get_postgresql_size first test`
`usage: manage.py influxdb_get_postgresql_size [-h] [--version] [-v {0,1,2,3}]`
`                                              [--settings SETTINGS]
                                              [--pythonpath PYTHONPATH]
                                              [--traceback] [--no-color]`
`manage.py influxdb_get_postgresql_size: error: unrecognized arguments: first test`

**Comment by Tyrdall** [comment]
@sLuvpreet33 Oh I'm afraid you think you can use influxdb as a Django database backend, right?
 If so please take a look at https://docs.djangoproject.com/en/1.11/ref/databases/

It seems the management command is out of use. I'll create a ticket.
