### ISSUE TITLE
Use influxdb with ssl

### ISSUE THREAD

**Issue by grangerp** [bitlabstudio/django-influxdb-metrics#2]
Hi,
it could be nice to to be able to use influxdb with ssl, it could be simple as adding params in settings and pass params to InfluxDBClient here, https://github.com/bitmazk/django-influxdb-metrics/blob/master/influxdb_metrics/utils.py#L10

I can send a pull request if you are interested.

Thanks

**Comment by mbrochh** [comment]
@grangerp sure thing! please send a pull request. happy to merge!
