### ISSUE TITLE
AttributeError on custom AUTH_USER_MODEL blocks admin page

### ISSUE THREAD

**Issue by cuneytcalishkan** [bitlabstudio/django-influxdb-metrics#26]
Hello,

I have a custom Profile model that is used for authentication which does not have the 'is_superuser' attribute. When I login from the admin page, I get the following trace on the logs and as a result an Internal Server Error with status 500.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/influxdb_metrics/middleware.py", line 50, in process_response
    self._record_time(request)
  File "/usr/local/lib/python3.4/dist-packages/influxdb_metrics/middleware.py", line 71, in _record_time
    if request.user.is_superuser:
AttributeError: 'Profile' object has no attribute 'is_superuser'

I will adapt my model to have this attribute but in my opinion this sort of AttributeError should not block the whole functionality of a site, instead maybe don't send that measurement tag.

 Version used is 1.3.3.

**Comment by Tyrdall** [comment]
@cuneytcalishkan It's strongly recommended to inherit from Django's `AbstractUser`: https://docs.djangoproject.com/en/2.0/topics/auth/customizing/

We'll stick to that recommendation and won't support any custom solutions.
