### ISSUE TITLE
When TIME_ZONE is set, the data is not stored in Influxdb

### ISSUE THREAD

**Issue by AdrianRibao** [bitlabstudio/django-influxdb-metrics#6]
Settings the TIME_ZONE setting makes the middleware fail to log the values.

Having:

`TIME_ZONE='Europe/Madrid'`

and executing the query:

`select * from django_request`

returns nothing.

As stated in https://docs.influxdata.com/influxdb/v0.12/write_protocols/write_syntax/#timestamps there is no need to send the timestamp. Also when is needed it should be in unixtime and nanoseconds.

Assuming this, it's safe to remove the time field from the data send to influxdb. 

I've created the PR #5 that fixes this issue.

**Comment by mbrochh** [comment]
@AdrianRibao amazing pull request. I have never worked with Docker, so please give me some time to review this. I am actually planning to upgrade our infrastructure to the latest InfluxDB and Grafana version this week or next week, after that I will take of this repo.

**Comment by AdrianRibao** [comment]
ok @mbrochh let me know if you need help :-)

**Comment by nilliams** [comment]
Hold on there, I don't this is a good idea.

It's not that the data is not 'stored in influxdb' it's that your times are out, so you're sending events an hour in the future etc (I hit this too).

You can query and see your data in this case by changing the time filter (influx by default filters to `now()`) e.g.

```
select * from django_auth_user_login where time < now() + 1h
```

And you should see your missing data.

However I think we still want to always send the time in case there is some network etc. error happening with Celery. That way once Celery is back up the tasks can get processed and the event times will be correct to the time they occurred.

See my PR which adds timezone awareness instead: https://github.com/bitmazk/django-influxdb-metrics/pull/10
